//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn
    {
        public int ilosc_kerami { get; set; }
        public Nullable<int> ilosc_gladz { get; set; }
        public Nullable<int> ilosc_gladz_luks { get; set; }
        public Nullable<int> ilosc_grunt { get; set; }
        public Nullable<int> ilosc_cement { get; set; }
        public Nullable<int> ilosc_tynk { get; set; }
        public Nullable<int> ilosc_wylewka { get; set; }
        public Nullable<int> ilosc_stiro { get; set; }
    }
}
