//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przedstawiciele
    {
        public int Id_sprzedawcy { get; set; }
        public string Faktura { get; set; }
        public string Klient { get; set; }
        public string NIP { get; set; }
    }
}
